# Generated by Django 5.0 on 2023-12-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("murder", "0002_alter_city_options_city_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenario",
            name="slug",
            field=models.SlugField(default="slug", max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="scenario",
            name="picture",
            field=models.ImageField(upload_to="scenario"),
        ),
        migrations.AlterField(
            model_name="scenario",
            name="thumbnail",
            field=models.ImageField(upload_to="scenario"),
        ),
    ]
